spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=admin
spring.security.user.password=admin123

jwt.secret=${JWT_SECRET:VGhpcy1pcy1hLWRldi1vbmx5LWp3dC1zZWNyZXQta2V5LWZvci1lY29tbWVyY2UtYmFja2VuZA==}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

server.port=8080
